// Derived from the Pi extension generated by `rtk init -g --agent pi` with `rtk 0.43.0`.
// RTK is licensed under Apache-2.0: https://github.com/rtk-ai/rtk

import { type ExtensionAPI, isToolCallEventType } from "@earendil-works/pi-coding-agent";

const REWRITE_TIMEOUT_MS = 2_000;
const MIN_SUPPORTED_RTK_MINOR = 23;
const AGENT_INSTRUCTIONS = `## RTK

RTK automatically rewrites supported non-interactive shell tool calls to simplify CLI output and reduce token usage.
If an RTK-rewritten command fails or behaves unexpectedly, retry only that command with \`RTK_DISABLED=1\` prefixed, for example \`RTK_DISABLED=1 git status\`.`;

export function getRewriteTarget(event: {
  toolName: string;
  input: Record<string, unknown>;
}): { command: string; apply(rewritten: string): void } | undefined {
  if (event.toolName === "bash") {
    if (typeof event.input.command !== "string" || event.input.command.trim() === "") return;
    return {
      command: event.input.command,
      apply: (rewritten) => {
        event.input.command = rewritten;
      },
    };
  }

  if (event.toolName === "exec_command") {
    // Interactive terminal commands should retain their exact command and terminal semantics.
    if (event.input.tty === true) return;
    if (typeof event.input.cmd !== "string" || event.input.cmd.trim() === "") return;
    return {
      command: event.input.cmd,
      apply: (rewritten) => {
        event.input.cmd = rewritten;
      },
    };
  }

  return undefined;
}

function parseSemver(raw: string): [number, number, number] | null {
  const match = raw.trim().match(/(\d+)\.(\d+)\.(\d+)/);
  if (!match) return null;
  return [
    Number.parseInt(match[1]!, 10),
    Number.parseInt(match[2]!, 10),
    Number.parseInt(match[3]!, 10),
  ];
}

export function extractRewrittenCommand(result: {
  code: number;
  stdout: string;
  killed: boolean;
}): string | null {
  // RTK's protocol returns 0 for an allowed rewrite and 3 for an advisory
  // rewrite that a permission-aware host would ask about. Both carry the valid
  // rewritten command on stdout. Exit 1 is unsupported/pass-through, while 2
  // defers a deny decision to the host; neither should rewrite the Pi tool call.
  if (result.killed || (result.code !== 0 && result.code !== 3)) return null;
  return result.stdout.trim() || null;
}

async function rewriteCommand(
  pi: ExtensionAPI,
  command: string,
  signal?: AbortSignal,
): Promise<string | null> {
  const result = await pi.exec("rtk", ["rewrite", command], {
    timeout: REWRITE_TIMEOUT_MS,
    ...(signal ? { signal } : {}),
  });
  return extractRewrittenCommand(result);
}

export default async function rtk(pi: ExtensionAPI) {
  const version = await pi.exec("rtk", ["--version"], { timeout: REWRITE_TIMEOUT_MS });
  if (version.code !== 0) {
    console.warn("[rtk] rtk binary not found in PATH — extension disabled");
    return;
  }

  const parsed = parseSemver(version.stdout.replace(/^rtk\s+/, ""));
  if (parsed) {
    const [major, minor] = parsed;
    if (major === 0 && minor < MIN_SUPPORTED_RTK_MINOR) {
      console.warn(
        `[rtk] rtk ${version.stdout.trim()} is too old (need >= 0.23.0) — extension disabled`,
      );
      return;
    }
  }

  pi.on("before_agent_start", (event) => ({
    systemPrompt: `${event.systemPrompt}\n\n${AGENT_INSTRUCTIONS}`,
  }));

  pi.on("tool_call", async (event, ctx) => {
    try {
      if (!isToolCallEventType("bash", event) && !isToolCallEventType("exec_command", event)) {
        return;
      }

      const target = getRewriteTarget(event);
      if (!target) return;
      if (target.command.startsWith("rtk ") || process.env.RTK_DISABLED === "1") return;

      // Only RTK's successful (0) and advisory (3) outcomes with non-empty stdout
      // produce a rewrite. Unsupported, denied, empty, or killed outcomes pass through.
      const rewritten = await rewriteCommand(pi, target.command, ctx.signal);
      if (rewritten && rewritten !== target.command) target.apply(rewritten);
    } catch (error) {
      console.warn("[rtk] unexpected error in tool_call handler; passing through command", error);
    }
  });
}
