// Derived from the Pi extension generated by `rtk init -g --agent pi` with `rtk 0.43.0`.
// RTK is licensed under Apache-2.0: https://github.com/rtk-ai/rtk

import { type ExtensionAPI, isToolCallEventType } from "@earendil-works/pi-coding-agent";

const REWRITE_TIMEOUT_MS = 2_000;
const MIN_SUPPORTED_RTK_MINOR = 23;
const AGENT_INSTRUCTIONS = `## RTK

RTK automatically rewrites CLI commands executed by \`bash\` tool for simplified output to reduce token usage.
If an RTK-rewritten command fails or behaves unexpectedly, retry only that command with \`RTK_DISABLED=1\` prefixed, for example \`RTK_DISABLED=1 git status\`.`;

function parseSemver(raw: string): [number, number, number] | null {
  const match = raw.trim().match(/(\d+)\.(\d+)\.(\d+)/);
  if (!match) return null;
  return [
    Number.parseInt(match[1]!, 10),
    Number.parseInt(match[2]!, 10),
    Number.parseInt(match[3]!, 10),
  ];
}

async function rewriteCommand(
  pi: ExtensionAPI,
  command: string,
  signal?: AbortSignal,
): Promise<string | null> {
  const result = await pi.exec("rtk", ["rewrite", command], {
    timeout: REWRITE_TIMEOUT_MS,
    ...(signal ? { signal } : {}),
  });
  if (result.killed || (result.code !== 0 && result.code !== 3)) return null;
  return result.stdout.trim() || null;
}

export default async function rtk(pi: ExtensionAPI) {
  const version = await pi.exec("rtk", ["--version"], { timeout: REWRITE_TIMEOUT_MS });
  if (version.code !== 0) {
    console.warn("[rtk] rtk binary not found in PATH — extension disabled");
    return;
  }

  const parsed = parseSemver(version.stdout.replace(/^rtk\s+/, ""));
  if (parsed) {
    const [major, minor] = parsed;
    if (major === 0 && minor < MIN_SUPPORTED_RTK_MINOR) {
      console.warn(
        `[rtk] rtk ${version.stdout.trim()} is too old (need >= 0.23.0) — extension disabled`,
      );
      return;
    }
  }

  pi.on("before_agent_start", (event) => ({
    systemPrompt: `${event.systemPrompt}

${AGENT_INSTRUCTIONS}`,
  }));

  pi.on("tool_call", async (event, ctx) => {
    try {
      if (!isToolCallEventType("bash", event)) return;

      const command = event.input.command;
      if (typeof command !== "string" || command.trim() === "") return;
      if (command.startsWith("rtk ") || process.env.RTK_DISABLED === "1") return;

      const rewritten = await rewriteCommand(pi, command, ctx.signal);
      if (rewritten && rewritten !== command) event.input.command = rewritten;
    } catch (error) {
      console.warn("[rtk] unexpected error in tool_call handler; passing through command", error);
    }
  });
}
